environment: prod
replicaCount: 1

vault:
  enabled: true
  secretPaths:
    postgres:
      path: "apps/data/prod/infra/postgres"
    mongodb:
      path: "apps/data/prod/infra/mongodb"
    redis:
      path: "apps/data/prod/infra/redis"
    kafka:
      path: "apps/data/prod/infra/kafka"
    identity-oidc:
      path: "apps/data/prod/services/am-identity"
    observability:
      path: "apps/data/prod/services/am-mcp-gateway"
    llm-api-keys:
      path: "apps/data/prod/services/am-mcp-gateway"

ingress:
  hosts:
    - host: am.asrax.in
      paths:
        - path: /tools
          pathType: Prefix

env:
  APP_ENV: prod
  QDRANT_URL: "https://qdrant.munish.org"
  TOOL_AGENT_ALLOW_WRITES: "false"
