environment: prod
replicaCount: 1

vault:
  enabled: true
  role: "am-backend-role"
  secretPaths:
    otel:
      path: "apps/data/prod/infra/observability"
    mongodb:
      path: "apps/data/prod/infra/mongodb"
    redis:
      path: "apps/data/prod/infra/redis"
    am-agents:
      path: "apps/data/prod/services/am-agents"

ingress:
  enabled: false

env:
  APP_ENV: prod
  AI_WRITE_TOOLS_ENABLED: "false"
  LLM_PLAN_A_MODEL: "together-llama-turbo"
  LITELLM_BASE_URL: "http://litellm.am-ai.svc.cluster.local:4000"
