apiVersion: am.argocd/v1
kind: ServiceDeploy
service: am-tool-agent
enabled: true
owners: agents
source:
  repo: am-agents
  path: tool-agent/argocd.yaml
chart:
  repoURL: https://github.com/AM-Portfolio/am-pipelines.git
  path: tool-agent/argocd.yaml
  targetRevision: main
helm:
  releaseName: am-tool-agent
  valuesPath: tool-agent/helm
valuesRepoURL: https://github.com/AM-Portfolio/am-agents.git
valuesTargetRevision: main
envs:
  prod:
    enabled: true
    namespace: am-apps-prod
