name: AM Fin Portfolio Agent Publish

on:
  push:
    branches: ["main", "develop", "test/**", "feature/**", "hotfix/**", "fix/**"]
    paths:
      - ".github/workflows/fin-portfolio-agent.yml"
      - "fin-portfolio-agent/**"
      - ".dockerignore"
  pull_request:
    branches: ["main", "develop", "test/**", "feature/**", "hotfix/**", "fix/**"]
    paths:
      - ".github/workflows/fin-portfolio-agent.yml"
      - "fin-portfolio-agent/**"
      - ".dockerignore"
  workflow_dispatch:

jobs:
  publish:
    name: Publish am-fin-agent
    permissions:
      contents: write
      packages: write
    uses: AM-Portfolio/am-pipelines/.github/workflows/central-build-publish-contabo.yml@main
    with:
      language: "python"
      working_directory: "fin-portfolio-agent"
      image_name: "am-fin-agent"
      build_context: "."
    secrets: inherit
